# Generated by Django 5.2.10 on 2026-06-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='form_type',
            field=models.CharField(choices=[('consultation', 'Consultation Form'), ('photography', 'Photography Consent'), ('botox', 'Anti-Wrinkle Consent'), ('prp', 'PRP Consent'), ('laser_reconsent', 'Laser Re-Consent'), ('booking_created', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('booking_amended', 'Booking Amended')], max_length=30),
        ),
    ]
