# Generated by Django 5.2.10 on 2026-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountcredit_credittransaction_prepaidbundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_type',
            field=models.CharField(choices=[('type_1', 'Type 1 – Always burns, never tans'), ('type_2', 'Type 2 – Easily burns, eventually gets a moderate tan'), ('type_3', 'Type 3 – Sometimes burns, quickly gets an average tan'), ('type_4', 'Type 4 – Rarely burns, quickly gets a deep tan'), ('type_5', 'Type 5 – Very rarely burns, consistent tan'), ('type_6', 'Type 6 – Never burns, consistent tan'), ('unknown', 'Unknown / Not assessed')], default='unknown', max_length=20),
        ),
    ]
