import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ---- Botox: add treatment area unit fields ----
        migrations.AddField(model_name="botoxconsentform", name="treatment_product_lot", field=models.CharField(blank=True, max_length=200)),
        migrations.AddField(model_name="botoxconsentform", name="units_forehead",     field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_glabella",     field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_crows_feet",   field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_jelly_roll",   field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_bunny_lines",  field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_gummy_smile",  field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_smokers_lines",field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_lip_flip",     field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_dao_jowls",    field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_chin",         field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_masseter",     field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_neck_bands",   field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="units_total",        field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="botoxconsentform", name="treatment_cost",     field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),

        # ---- PRP Consent Form ----
        migrations.CreateModel(
            name="PRPConsentForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("completed_by_practitioner", models.BooleanField(default=False)),
                ("signature", models.TextField(help_text="Base64-encoded PNG of the client signature.")),
                ("full_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(blank=True)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=200)),
                ("emergency_contact_phone", models.CharField(blank=True, max_length=20)),
                ("blood_disorders", models.BooleanField(default=False)),
                ("on_anticoagulants", models.BooleanField(default=False)),
                ("active_infection", models.BooleanField(default=False)),
                ("autoimmune_disease", models.BooleanField(default=False)),
                ("history_of_cancer", models.BooleanField(default=False)),
                ("skin_conditions", models.BooleanField(default=False)),
                ("recent_vaccination", models.BooleanField(default=False)),
                ("communicable_diseases", models.BooleanField(default=False)),
                ("keloid_scarring", models.BooleanField(default=False)),
                ("current_medications", models.TextField(blank=True)),
                ("other_conditions", models.TextField(blank=True)),
                ("treatment_areas", models.CharField(blank=True, max_length=300)),
                ("expectations", models.TextField(blank=True)),
                ("is_pregnant", models.BooleanField(default=False)),
                ("is_breastfeeding", models.BooleanField(default=False)),
                ("has_medical_problems", models.BooleanField(default=False)),
                ("on_medication", models.BooleanField(default=False)),
                ("has_allergies", models.BooleanField(default=False)),
                ("previous_prp", models.BooleanField(default=False)),
                ("yes_details", models.TextField(blank=True)),
                ("consent_procedure", models.BooleanField(default=False)),
                ("consent_risks", models.BooleanField(default=False)),
                ("consent_results", models.BooleanField(default=False)),
                ("consent_aftercare", models.BooleanField(default=False)),
                ("consent_photos", models.BooleanField(default=False)),
                ("consent_privacy", models.BooleanField(default=False)),
                ("consent_agreement", models.BooleanField(default=False)),
                ("client_signed", models.BooleanField(default=False)),
                ("client_signed_at", models.DateTimeField(blank=True, null=True)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                ("product_batch", models.CharField(blank=True, max_length=200)),
                ("vials_drawn", models.CharField(blank=True, max_length=20)),
                ("centrifuge_details", models.CharField(blank=True, max_length=200)),
                ("application_method", models.CharField(blank=True, max_length=200)),
                ("treatment_areas_operator", models.TextField(blank=True)),
                ("next_appointment", models.CharField(blank=True, max_length=200)),
                ("treatment_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("operator_notes", models.TextField(blank=True)),
                ("operator_signature", models.TextField(blank=True)),
                ("operator_signed", models.BooleanField(default=False)),
                ("operator_signed_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="prpconsentform_forms", to=settings.AUTH_USER_MODEL)),
                ("practitioner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prpconsentform_completed_as_practitioner", to=settings.AUTH_USER_MODEL)),
                ("operator_signed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prp_operator_completions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-completed_at"], "verbose_name": "PRP Consent Form"},
        ),

        # ---- Laser Re-Consent ----
        migrations.CreateModel(
            name="LaserReConsent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("changes_consultation_form", models.BooleanField(default=False)),
                ("changes_medication", models.BooleanField(default=False)),
                ("changes_uv_exposure", models.BooleanField(default=False)),
                ("active_tan", models.BooleanField(default=False)),
                ("changes_detail", models.TextField(blank=True)),
                ("client_feedback", models.TextField(blank=True)),
                ("consent_proceed", models.BooleanField(default=False)),
                ("client_signature", models.TextField()),
                ("client_signed_at", models.DateTimeField(blank=True, null=True)),
                ("treatment_notes", models.TextField(blank=True)),
                ("operator_signature", models.TextField(blank=True)),
                ("operator_signed", models.BooleanField(default=False)),
                ("operator_signed_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="laser_reconsents", to=settings.AUTH_USER_MODEL)),
                ("practitioner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="laser_reconsents_as_practitioner", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-completed_at"], "verbose_name": "Laser Re-Consent"},
        ),
    ]
