# Generated by Django 5.2.10 on 2026-06-14 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_system', '0002_botox_areas_prp_laser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prpconsentform',
            name='completed_by_practitioner',
            field=models.BooleanField(default=False, help_text='True if practitioner completed this on behalf of the client.'),
        ),
        migrations.AlterField(
            model_name='prpconsentform',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='The staff member who completed this, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completed_as_practitioner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prpconsentform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
