# Generated by Django 5.2.10 on 2026-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_system', '0004_guardian_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botoxconsentform',
            name='guardian_signature',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG of guardian/parent signature.'),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='guardian_signature',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG of guardian/parent signature.'),
        ),
        migrations.AlterField(
            model_name='photographyconsent',
            name='guardian_signature',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG of guardian/parent signature.'),
        ),
        migrations.AlterField(
            model_name='prpconsentform',
            name='guardian_signature',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG of guardian/parent signature.'),
        ),
    ]
