# Generated by Django 5.2.10 on 2026-05-22 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcategory',
            name='colour',
            field=models.CharField(default='#7F77DD', help_text='Hex colour code for dashboard display, e.g. #A3B4C5', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #A3B4C5', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
