# Generated by Django 5.2.10 on 2026-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_treatmentgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['category__order', 'category__id', 'group__order', 'group__name', 'order', 'name']},
        ),
        migrations.AlterField(
            model_name='treatmentgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
