# Generated by Django 5.2.10 on 2026-04-16 21:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('summary', models.TextField(blank=True, help_text='Short description shown on the card (optional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the page')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
